before:
  hooks:
    - go mod tidy
builds:
- id: "terraform-provider-basexform"
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  goarm:
    - 6
    - 7
  flags:
    - -trimpath
  ldflags:
    - -s -w
  env:
    - CGO_ENABLED=0
archives:
- id: "terraform-provider-basexform"
  builds:
    - "terraform-provider-basexform"
  format: zip
  files:
    - LICENSE
    - README.md

checksum:
  name_template: 'terraform-provider-basexform_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    args: ["--batch", "--yes", "--detach-sign", "--local-user", "${GPG_FINGERPRINT}", "--output", "${signature}", "${artifact}"]
